version: '2.1'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5405:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: afvalophaalgebieden
      POSTGRES_USER: afvalophaalgebieden

  web:
    build: ./web
    ports:
      - "8095:8000"
    links:
      - database
    environment:
      DB_PORT_5432: 5432
      DB_HOST: database
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "app"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
    command: >
      bash -c "/app/docker-wait.sh \
              && /app/docker-migrate.sh \
              && /app/docker-run.sh"