database:
  build: ./postgres
  ports:
    - "5405:5432"
  environment:
    POSTGRES_HOST: localhost
    POSTGRES_PASSWORD: insecure
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres

web:
  build: ./web
  ports:
    - "8102:8000"
  links:
    - database:database
  environment:
    DOCKER_PORT: 5432
    DOCKER_HOST: database
