version: '3.0'
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5405:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: afvalophaalgebieden
      POSTGRES_USER: afvalophaalgebieden

  afvalophaalgebieden:
    build: .
    ports:
      - "8095:8000"
    links:
      - database
    environment:
      DB_HOST: database
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "app"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
