version: '3.0'
services:
  database:
    image: amsterdam/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: afvalophaalgebieden
    volumes:
      - ./backups:/tmp/backups

  importer:
    image: repo.data.amsterdam.nl/datapunt/afvalophaalgebieden:${ENVIRONMENT}
    links:
      - database
    environment:
      DB_NAME: afvalophaalgebieden
      DB_USER: afvalophaalgebieden
      DB_HOST: database
      DB_PASSWORD: insecure
      DB_PORT_5432: 5432
      DATAPUNT_API_URL:
    command: >
      bash -c "./docker-import-db.sh"
