version: '3.0'
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: afvalophaalgebieden
    volumes:
      - ./backups:/tmp/backups

  importer:
    image: ${DOCKER_REGISTRY_HOST}/datapunt/afvalophaalgebieden:${ENVIRONMENT}
    links:
      - database
    environment:
      DB_NAME: afvalophaalgebieden
      DB_USER: afvalophaalgebieden
      DB_HOST: database
      DB_PASSWORD: insecure
      DATAPUNT_API_URL:
    command: >
      bash -c "./docker-import-db.sh"
