version: '3.0'
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: afvalophaalgebieden

  tests:
    build: ..
    links:
      - database
    environment:
      DB_NAME: afvalophaalgebieden
      DB_USER: afvalophaalgebieden
      DB_HOST: database
      DB_PASSWORD: insecure
    command: >
      bash -c "/app/docker-wait.sh && python /app/tests.py"
